version: "3.8"

services:
  traefik:
    container_name: ${APP_NAME}-traefik
    image: traefik:latest
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    environment:
      - DOMAIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "80:80"
    security_opt:
      - no-new-privileges:true
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.entrypoints: web
      traefik.http.routers.traefik.rule: Host(`traefik.${DOMAIN}`)
      traefik.http.routers.traefik.service: api@internal
    restart: unless-stopped

  database:
    container_name: ${APP_NAME}-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS:-dev}
      MYSQL_DATABASE: ${DB_NAME:-dev}
    volumes:
      - ./storage/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    restart: unless-stopped
    depends_on:
      - traefik

  backend:
    container_name: ${APP_NAME}-backend
    build:
      context: .
      args:
        UID: ${UID:-1000}
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: ${PHP_OPCACHE_VALIDATE_TIMESTAMPS:-1}
    volumes:
      - ./backend:/var/api
      - .env:/var/api/.env
      - .docker/php.ini:/usr/local/etc/php/conf.d/php.ini
      - .docker/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
    working_dir: /var/api
    command:
      - bash
      - -c
      - |
        composer install --prefer-dist --no-interaction
        php-fpm
    restart: unless-stopped
    depends_on:
      - database

  frontend:
    container_name: ${APP_NAME}-frontend
    image: node:latest
    volumes:
      - ./frontend:/var/www
    environment:
      WDS_SOCKET_PORT: 0
    working_dir: /var/www
    command:
      - bash
      - -c
      - |
        yarn
        yarn build
        yarn start
    labels:
      traefik.enable: true
      traefik.http.routers.frontend.entrypoints: web
      traefik.http.routers.frontend.rule: Host(`${DOMAIN}`,`www.${DOMAIN}`)
      traefik.http.services.frontend.loadbalancer.server.port: 3000
    restart: unless-stopped
    depends_on:
      - backend
  
  nginx:
    container_name: ${APP_NAME}-nginx
    image: nginx:latest
    environment:
      - DOMAIN
    volumes:
      - ./frontend/build:/var/www/public
      - ./backend/public:/var/api/public
      - .docker/nginx.conf:/etc/nginx/nginx.conf
      - .docker/api.conf.template:/etc/nginx/templates/default.conf.template
      - ./logs/nginx:/var/log/nginx
    labels:
      traefik.enable: true
      traefik.http.routers.backend.entrypoints: web
      traefik.http.routers.backend.rule: Host(`api.${DOMAIN}`)
    restart: unless-stopped
    depends_on:
      - backend

  portainer:
    container_name: ${APP_NAME}-portainer
    image: portainer/portainer-ce
    volumes:
      - ./storage/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: true
      traefik.http.routers.portainer.entrypoints: web
      traefik.http.routers.portainer.rule: Host(`portainer.${DOMAIN}`)
      traefik.http.services.portainer.loadbalancer.server.port: 9000
    restart: unless-stopped
    depends_on:
      - traefik
